### ISSUE TITLE
assembleMTgenome.py error

### ISSUE THREAD

**Issue by l0ka** [mitoNGS/MToolBox#56]
Running MToolBox (with default parameters) on 2 samples returns this error:

```
##### ASSEMBLING MT GENOMES WITH ASSEMBLEMTGENOME...

WARNING: values of tail < 5 are deprecated and will be replaced with 5

[bam_sort_core] merging from 2 files...
[bam_translate] RG tag "sample" on read "HISEQ:3:C1YCFACXX:8:1101:15692:70202" encountered with no corresponding entry in header, tag lost. Unknown tags are only reported once per input file for each tag ID.
[bam_translate] RG tag "sample" on read "HISEQ:94:C2D59ACXX:4:2304:5360:11995" encountered with no corresponding entry in header, tag lost. Unknown tags are only reported once per input file for each tag ID.
[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
Traceback (most recent call last):
  File "MToolBox/assembleMTgenome.py", line 443, in <module>
    mut_events = mtvcf_main_analysis(mt_table, sam_file, sample_name, tail=tail)
  File "/tools/MToolBox-master/MToolBox/mtVariantCaller.py", line 856, in mtvcf_main_analysis
    qs1.append(median(qs2))
  File "tools/MToolBox-master/MToolBox/mtVariantCaller.py", line 402, in median
    m1 = sorted(l)[(len(l)/2)+1-1]
IndexError: list index out of range
[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000

##### GENERATING VCF OUTPUT...
Reference sequence used for VCF: RSRS

##### PREDICTING HAPLOGROUPS AND ANNOTATING/PRIORITIZING VARIANTS...

Haplogroup predictions based on RSRS Phylotree build 17
Unable to compute haplogroup. ExitYour best results file is  mt_classification_best_results.csv

Loading contig sequences from file PM21_case-contigs.fasta
Your best results file is  mt_classification_best_results.csv

Loading contig sequences from file PM21_ctrl-contigs.fasta
Loaded 1 contig sequences

Aligning Contigs to mtDNA reference genome...

______________________________
**** Deleting SNP: 3107d
______________________________
**** Deleting SNP: 523-524d

Sequence haplogroup assignment

Classification according to tree: /MToolBox/data/phylotree_r17.pickle
genome_state is  incomplete
OrderedDict([('J1b1a1', (58, 58, 58))])
====================
I'm looking for J1b1a1
------------------------------
Contig alignment to MHCS and rCRS
Aligning contigs to MHCS SeqDiff object
______________________________
**** Deleting SNP: 3107d
rCRS SeqDiff object
______________________________
**** Deleting SNP: 3107d
Merging seq_diffs...
Writing results for sequence PM21_ctrl
Parsing pathogenicity table...
Parsing variability data...
Parsing info about haplogroup-defining sites...
Parsing info about haplogroup assignments...
/PM21/OUT_PM21_ctrl/PM21_ctrl_merged_diff.csv
Parsing variant data for sample PM21_ctrl...
Best haplogroup predictions for sample PM21_ctrl : ['J1b1a1']
Functional annotation for haplogroup J1b1a1
Looking for prioritized variants...

Prioritization analysis done.

cat: '*coverage.txt': No such file or directory
awk: cmd. line:1: fatal: cannot open file `*annotation.csv' for reading (No such file or directory)
awk: cmd. line:1: fatal: cannot open file `*annotation.csv' for reading (No such file or directory)
awk: cmd. line:1: fatal: cannot open file `*annotation.csv' for reading (No such file or directory)
Traceback (most recent call last):
  File "/MToolBox/summary.py", line 54, in <module>
    dic_cov[i[1]]=i[7]
IndexError: list index out of range

Analysis completed!
```

It says "Analysis completed!", but the summary file is empty.

**Comment by clody23** [comment]
This issue is now solved with latest fixes.  See issue #64.
