### ISSUE TITLE
Need help with error: no VCF_dict_tmp

### ISSUE THREAD

**Issue by MatthewP-Newbee** [mitoNGS/MToolBox#58]
Hi, I used install.sh to installed this sofeware, how ever when I test it by using test file of this software, it seems missing file/dir VCF-dict_tmp. I think there may be some installed problem that I don't know. Here is the error info:
##### GENERATING VCF OUTPUT...
Traceback (most recent call last):
  File "/ifs1/Reotech/user/pengguoyu/software/MToolBox-master/MToolBox/VCFoutput.py", line 36, in <module>
    VCF_dict = ast.literal_eval(open('VCF_dict_tmp', 'r').read())
IOError: [Errno 2] No such file or directory: **'VCF_dict_tmp'**

Loading contig sequences from file simulation100X-contigs.fasta
Unable to compute haplogroup. ExitHeteroplasmy data file (**'VCF_dict_tmp'**) not found. HF will not be reported in the output.
Parsing pathogenicity table...
Parsing variability data...
Parsing info about haplogroup-defining sites...
Parsing info about haplogroup assignments...
**No annotation.csv found**. Exit

**Comment by sean-boothby** [comment]
Hey Matthew, been working on the same problem.

I think the issue has to do with the MToolBox.sh file calling for a file in the directory /bin/samtools-1.3
Seems like it the bash script calls for samtoolsexe which does not exist and from that point there are many issues that occur.

If you have solved this I would really appreciate your help. I will also keep anything I find out updated here.

**Comment by btrspg** [comment]
I have the same question, but I found a few steps former for that
```
Traceback (most recent call last):
  File "/wes/chenyl/projects/MToolBox/MToolBox/assembleMTgenome.py", line 443, in <module>
    mut_events = mtvcf_main_analysis(mt_table, sam_file, sample_name, tail=tail)
  File "/wes/chenyl/projects/MToolBox/MToolBox/mtVariantCaller.py", line 856, in mtvcf_main_analysis
    qs1.append(median(qs2))
  File "/wes/chenyl/projects/MToolBox/MToolBox/mtVariantCaller.py", line 402, in median
    m1 = sorted(l)[(len(l)/2)+1-1]
IndexError: list index out of range
```
