### ISSUE TITLE
vcfoutput bug

### ISSUE THREAD

**Issue by Pilibeibei** [mitoNGS/MToolBox#85]
When I used the updated 1.1 version, the analysis running smoothly and I got test.vcf file. However, when I try the latest version 1.2, it showed errors. I got all result files except for test.vcf. when I use vcf_dict_tmp to run VCFoutput.py, it shows:

Reference sequence used for VCF: RCRS
Traceback (most recent call last):
  File "/home/MToolBox-master/MToolBox/VCFoutput.py", line 38, in <module>
    VCFoutput(VCF_dict, reference=reference_sequence, name=sample_vcf_name)
  File "/home/MToolBox-master/MToolBox/mtVariantCaller.py", line 935, in VCFoutput
    i._sample_indexes[sample][0].append(genotype)
AttributeError: 'int' object has no attribute 'append'

Please help.

Thanks

**Comment by clody23** [comment]
Hi,
can you please try again a git pull to upload your local copy of MToolBox? Since the  v. 1.2  release  we have done additional fixes, which might solve your problem. 

Also, can you please run using one list file per sample. The current version of MToolBox might have problems in handling multiple samples indeed. This is going to be solved with the snakemake version of MToolBox, that we are planning to release soon.

Best wishes,
Claudia

**Comment by Pilibeibei** [comment]
Thanks, Claudia,

I think that's the case. When I run one list file per sample, it works, and I get vcf_dict_tmp and sample1.vcf. Then, I have to put the sample1.vcf in another folder so when I run the second list file iI can get sample2.vcf, otherwise I can only get vcf_dict_tmp and see the same error for VCFoutput.py as 

Traceback (most recent call last):
  File "/home/MToolBox-master/MToolBox/VCFoutput.py", line 38, in <module>
    VCFoutput(VCF_dict, reference=reference_sequence, name=sample_vcf_name)
  File "/home/MToolBox-master/MToolBox/mtVariantCaller.py", line 935, in VCFoutput
    i._sample_indexes[sample][0].append(genotype)
AttributeError: 'int' object has no attribute 'append'

I have several hundreds of samples for analysis, it would be great if you can fix that problem for multiple samples. 

Thanks

J

**Comment by bjstewart1** [comment]
I am also getting this error with MToolBox-1.2.1
Works for one sample, but will not produce a vcf file when tasked with multiple input samples.

**Comment by em-arpy** [comment]
I have downloaded the latest release and have the same issue. The vcf file generates for a single sample and not for multiple.

**Comment by Qinqiword** [comment]
Hi,

I also encountered the same problem with MToolBox-1.2.1. 

When I run one list file per sample, it works，when  put 2 samples in one list, it also works,  but when I put 20 samples in one list file, it will report as follows error：

```##### GENERATING VCF OUTPUT...
Reference sequence used for VCF: RCRS
Traceback (most recent call last):
  File "/home/gengzhx/software/MToolBox-1.2.1/MToolBox/VCFoutput.py", line 38, in <module>
    VCFoutput(VCF_dict, reference=reference_sequence, name=sample_vcf_name)
  File "/home/gengzhx/software/MToolBox-1.2.1/MToolBox/mtVariantCaller.py", line 868, in VCFoutput
    i._sample_indexes[sample][0].append(aplotype)
AttributeError: 'int' object has no attribute 'append'
```

In fact, I have several thousands of  samples. So I‘m looking forward to fixing this error . Or is it possible to generate a gvcf file for each sample ?  In this way, more variation information can be retained when merging population data.



Thanks

Wangj

**Comment by adarsh-pp** [comment]
> Hi,
> 
> I also encountered the same error with `MToolBox-1.2.1`.
> 
> When I run one list file per sample, it works，when put 2 samples in one list, it also works, but when I put 20 samples in one list file, it shows：
> 
> ```
> Reference sequence used for VCF: RCRS
> Traceback (most recent call last):
>   File "/home/gengzhx/software/MToolBox-1.2.1/MToolBox/VCFoutput.py", line 38, in <module>
>     VCFoutput(VCF_dict, reference=reference_sequence, name=sample_vcf_name)
>   File "/home/gengzhx/software/MToolBox-1.2.1/MToolBox/mtVariantCaller.py", line 868, in VCFoutput
>     i._sample_indexes[sample][0].append(aplotype)
> AttributeError: 'int' object has no attribute 'append'
> ```
> 
> **In fact, I have several thousands of samples. So I‘m looking forward to fixing this error. Alternatively, is it possible to generate a gvcf file for each sample? In this way, more variation information can be retained when merging population data.**
> 
> Thanks
> 
> Wangj

Hi
Was this issue sorted out?
I am trying to run multiple samples with version 1.2.1 and I am getting same error. It is not able to generate a vcf file.

**Comment by adarsh-pp** [comment]
@Pilibeibei @clody23 @Qinqiword
